# Generated by Django 6.0.3 on 2026-03-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai_links",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ai_links",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
